- name: brave curl keyring
  shell: curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
- name: brave echo release list
  shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"| tee /etc/apt/sources.list.d/brave-browser-release.list

- name: Run the equivalent of "apt update" as a separate step
  apt:
    update_cache: yes
    
- name: Install brave-browser
  apt: name=brave-browser

- name: create wayland shortcut for brave
  shell: echo "brave-browser --enable-features=UseOzonePlatform --ozone-platform=wayland" > /usr/bin/brave-browser-wayland

- name: make wayland shortcut for brave executable
  shell: chmod +x /usr/bin/brave-browser-wayland
