- name: Download oh-my-bash
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh
    dest: "{{ temp_working_directory }}/install-oh-my-bash.sh"

- name: make oh-my-bash executable
  shell: chmod +x "{{ temp_working_directory }}/install-oh-my-bash.sh"

- name: Install oh-my-bash
  shell: "{{ temp_working_directory }}/install-oh-my-bash.sh"
