- name: Create temporary vault password file
  copy:
    content: "{{ vault_password }}"
    dest: "/tmp/vault_password"
    mode: '0600'
    
- name: Clone the git repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    version: 'prime-ubuntu-sway'
    update: yes

- name: Decrypt and copy private key
  command: >
    ansible-vault decrypt {{ encrypted_file_path }} --output={{ decrypted_file_path }} --vault-password-file=/tmp/vault_password
  args:
    creates: "{{ decrypted_file_path }}"

- name: Copy public key
  command: >
    cp '{{ ssh_path }}/id_rsa.pub' '{{ home_directory }}/.ssh/id_rsa.pub'
    
- name: Remove temporary vault password file
  file:
    path: "/tmp/vault_password"
    state: absent
