- hosts: localhost
  vars:
    user_name: ramboe
    home_directory: /home/{{ user_name }}
    repo_url: 'https://github.com/ramboe/config-arch.git'
    repo_dest: '{{ home_directory }}/Documents/config-arch'
    ssh_path: '{{ repo_dest }}/ansible/ssh'
    encrypted_file_path: '{{ ssh_path }}/id_rsa_encrypted'
    decrypted_file_path: '{{ home_directory }}/.ssh/id_rsa'
  
  tasks:
    - name: Clone the git repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: 'prime-ubuntu-sway'
        update: yes

    - name: Decrypt and copy private key
      command: >
        ansible-vault decrypt {{ encrypted_file_path }} --output={{ decrypted_file_path }}
      args:
        creates: "{{ decrypted_file_path }}"

    - name: Copy public key
      command: >
        cp '{{ ssh_path }}/id_rsa.pub' '{{ home_directory }}/.ssh/id_rsa.pub'
