- hosts: localhost
  vars:
    user_name: ramboe
    home_directory: /home/{{ user_name }}
    temp_working_directory: "{{ home_directory }}/Downloads"
  
  vars_prompt:
    - name: vault_password
      prompt: Enter vault password
      private: yes

  become: true
  tasks:
    - name: Run the equivalent of "apt update" as a separate step
      apt:
        update_cache: yes

    - name: import create directories
      include_tasks: 'ansible-tasks/create-directories.yml'
      
    - name: Install tmux
      apt: name=tmux
    - name: Install curl
      apt: name=curl
    - name: Install gpg
      apt: name=gpg
    - name: Install wget
      apt: name=wget
    - name: Install wireguard
      apt: name=wireguard
    - name: Install git
      apt: name=git
    - name: Install apt-transport-https
      apt: name=apt-transport-https

    - name: Setup ssh
      include_tasks: 'ansible-tasks/setup-ssh.yml'
      vars:
        user_name: ramboe
        home_directory: /home/{{ user_name }}
        repo_url: 'https://github.com/ramboe/config-arch.git'
        repo_dest: '{{ home_directory }}/Documents/config-arch'
        ssh_path: '{{ repo_dest }}/ansible/ssh'
        encrypted_file_path: '{{ ssh_path }}/id_rsa_encrypted'
        decrypted_file_path: '{{ home_directory }}/.ssh/id_rsa'
        
    - name: Setup wireguard
      include_tasks: 'ansible-tasks/setup-wireguard.yml'
      vars:
        user_name: ramboe
        home_directory: /home/{{ user_name }}
        repo_url: 'https://github.com/ramboe/config-arch.git'
        repo_dest: '{{ home_directory }}/Documents/config-arch'
        wireguard_repo_path: '{{ repo_dest }}/ansible/wireguard'
        encrypted_files:
          - sweden-wg0-encrypted.conf
          - sweden-wg1-encrypted.conf
          - sweden-wg2-encrypted.conf
          - finland-wg0-encrypted.conf
        decrypted_file_path: '/etc/wireguard'
      #        vault_password: '{{ vault_password }}'
      
      
      #    - name: import nvchad
      #      include_tasks: 'ansible-tasks/install-nvchad.yml'
      #    - name: import oh-my-bash
      #      include_tasks: 'ansible-tasks/install-oh-my-bash.yml'
      #    - name: import microsoft-edge
      #      include_tasks: 'ansible-tasks/install-microsoft-edge.yml'
      #    - name: import google-chrome
      #      include_tasks: 'ansible-tasks/install-google-chrome.yml'
      #    - name: import further packages
      #      include_tasks: 'ansible-tasks/install-further-packages.yml'
      #    - name: import brave
      #      include_tasks: 'ansible-tasks/install-brave.yml'
      #    - name: import vscode
      #      include_tasks: 'ansible-tasks/install-vscode.yml'
      #
      #
      #    - name: Install chromium
      #      apt: name=chromium
      #    - name: Install dotnet-sdk-8.0
      #      apt: name=dotnet-sdk-8.0
      #    - name: Install keepassxc
      #      apt: name=keepassxc
      #    - name: Install flameshot
      #      apt: name=flameshot
      #    - name: Install obs-studio
      #      apt: name=obs-studio
      #    - name: az-cli
      #      shell: curl -sL https://aka.ms/InstallAzureCLIDeb | bash
      
      
      # ------------------ - config import
      
      #    - name: CHECKOUT config-arch
      #      ansible.builtin.git:
      #        repo: 'https://github.com/ramboe/config-arch.git'
      #        dest: "{{ home_directory }}/Documents/config-arch"
      #        version: 'prime'
      
      # tmux config config
      
      # obs config
#    - name: copy obs config
#      shell: "cp -r {{ home_directory }}/Documents/config-arch/.config/obs-studio {{ home_directory }}/.config/obs-studio"
