- hosts: localhost
  vars:
    user_name: ramboe
    home_directory: /home/{{ user_name }}
    temp_working_directory: "{{ home_directory }}/Downloads"


  become: true
  tasks:
    - include: 'ansible-tasks/create-directories.yml'
    - include: 'ansible-tasks/install-brave.yml'
    - include: 'ansible-tasks/install-further-packages.yml'
    - include: 'ansible-tasks/install-google-chrome.yml'
    - include: 'ansible-tasks/install-microsoft-edge.yml'
    - include: 'ansible-tasks/install-nvchad.yml'
    - include: 'ansible-tasks/install-oh-my-bash.yml'
    - include: 'ansible-tasks/install-vscode.yml'

    - name: Install tmux
      apt: name=tmux

    - name: Install curl
      apt: name=curl

    - name: Install gpg
      apt: name=gpg
    - name: Install wget
      apt: name=wget

    - name: az-cli
      shell: curl -sL https://aka.ms/InstallAzureCLIDeb | bash
    
    - name: Install apt-transport-https
      apt: name=apt-transport-https
    - name: Install wireguard
      pacman: name=wireguard
    - name: Install chromium
      apt: name=chromium
    - name: Install dotnet-sdk-8.0
      apt: name=dotnet-sdk-8.0
    - name: Install keepassxc
      apt: name=keepassxc
    - name: Install flameshot
      apt: name=flameshot
    - name: Install obs-studio
      apt: name=obs-studio
    

    
    # ------------------ - config import
    
    - name: CHECKOUT config-arch
      ansible.builtin.git:
        repo: 'https://github.com/ramboe/config-arch.git'
        dest: "{{ home_directory }}/Documents/config-arch"
        version: 'prime'
      
      # tmux config config
      
      # obs config
    - name: copy obs config
      shell: "cp -r {{ home_directory }}/Documents/config-arch/.config/obs-studio {{ home_directory }}/.config/obs-studio"
