- hosts: localhost
  vars:
    user_name: ramboe
    home_directory: /home/{{ user_name }}
    repo_url: 'https://github.com/ramboe/config-arch.git'
    repo_dest: '{{ home_directory }}/Documents/config-arch'
    wireguard_repo_path: '{{ repo_dest }}/ansible/wireguard'
    encrypted_files:
      - sweden/sweden-wg0-encrypted.conf
      - sweden/sweden-wg1-encrypted.conf
      - sweden/sweden-wg2-encrypted.conf
    decrypted_file_path: '/etc/wireguard'
  
  become: true
  tasks:
    - name: Clone the git repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: 'prime-ubuntu-sway'
        update: yes

    - name: Decrypt and copy files
      command: >
        ansible-vault decrypt {{ wireguard_repo_path }}/{{ item }} --output={{ decrypted_file_path }}/{{ item | replace('sweden/', '') | replace('-encrypted.conf', '.conf') }}
      args:
        creates: "{{ decrypted_file_path }}/{{ item | replace('sweden/', '') | replace('-encrypted.conf', '.conf') }}"
      loop: "{{ encrypted_files }}"

    - name: Copy vpn-toggle-script
      command: >
        cp '{{ wireguard_repo_path }}/vpn-toggle' '/usr/bin/vpn-toggle'

    - name: make vpn-toggle-script executable
      command: >
        chmod +x /usr/bin/vpn-toggle